# Generated by Django 4.0.2 on 2022-08-06 13:07

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import djmoney.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_name', models.CharField(max_length=20)),
                ('website_link', models.URLField(blank=True)),
                ('membership_number', models.CharField(blank=True, max_length=30)),
                ('membership_type', models.CharField(choices=[('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('ANNUAL', 'Annual'), ('FIXED', 'Fixed-term'), ('LIFETIME', 'Lifetime'), ('CUSTOM', 'Custom')], default='MONTHLY', max_length=8)),
                ('custom_period', models.PositiveIntegerField(blank=True, null=True)),
                ('custom_unit', models.CharField(blank=True, choices=[('DAY', 'Days'), ('WEEK', 'Weeks'), ('MONTH', 'Months'), ('YEAR', 'Years')], max_length=5, null=True)),
                ('renewal_date', models.DateField(blank=True, null=True)),
                ('reminder', models.BooleanField(default=False)),
                ('minimum_term', models.DateField(blank=True, null=True)),
                ('free_trial_expiry', models.DateField(blank=True, null=True)),
                ('cost_currency', djmoney.models.fields.CurrencyField(choices=[('AED', 'AED'), ('ARS', 'ARS'), ('AUD', 'AUD'), ('BDT', 'BDT'), ('BRL', 'BRL'), ('CAD', 'CAD'), ('CHF', 'CHF'), ('CLP', 'CLP'), ('CNY', 'CNY'), ('COP', 'COP'), ('CZK', 'CZK'), ('DKK', 'DKK'), ('EGP', 'EGP'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('HKD', 'HKD'), ('IDR', 'IDR'), ('ILS', 'ILS'), ('INR', 'INR'), ('IRR', 'IRR'), ('JPY', 'JPY'), ('KRW', 'KRW'), ('MXN', 'MXN'), ('MYR', 'MYR'), ('NGN', 'NGN'), ('NOK', 'NOK'), ('NZD', 'NZD'), ('PHP', 'PHP'), ('PKR', 'PKR'), ('PLN', 'PLN'), ('RON', 'RON'), ('RUB', 'RUB'), ('SAR', 'SAR'), ('SEK', 'SEK'), ('SGD', 'SGD'), ('THB', 'THB'), ('TRY', 'TRY'), ('TWD', 'TWD'), ('USD', 'USD'), ('VEF', 'VEF'), ('VND', 'VND'), ('ZAR', 'ZAR')], default='USD', editable=False, max_length=3)),
                ('cost', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='USD', max_digits=11)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
